### PR TITLE
Styled components

### PR DESCRIPTION
**Pull request by ajhyndman**
Prerequisites:

* [x] #2 Prettier
* [x] #4 Flow
* [x] #5 Storybook

### CODE REVIEW

**Comment by jayce-leathers** [comment]
@ajhyndman What are your thoughts on separating the styled-components out into separate files. I've only used styled-components a little but thought that it was cleaner to define styling separately and import into the component.

**Comment by ajhyndman** [comment]
@jayce-leathers Yeah, I guess I don't have a strong opinion there.

In my mind, the file structure is less interesting than the composition of the components themselves.  I can try breaking them apart, and see how that feels.

**Comment by jayce-leathers** [comment]
I don't have a strong opinion either. Just a hunch that as the system grows it will be easier to organize and share styles if we pull them out into their own files.

**Comment by ajhyndman** [comment]
@jayce-leathers I finally got around to pushing another commit with the styled component definitions extracted.  What do you think?

**Pull request merged**
